In [5]:
# list operation in python
print("Python list operations:")
a = [1,2,3]
b = [4,5,6]
print("a+b:", a+b)

try: 
    print(a*b)
except TypeError:
    print("a*b has no meaning for Python lists")


Python list operations:
a+b: [1, 2, 3, 4, 5, 6]
a*b has no meaning for Python lists


In [7]:
# list operation in numpy

import numpy as np

print("numpy array operations:") 
c = np.array([1,2,3])
d = np.array([4,5,6]) 
print("c+d:", c+d) 
print("c*d:", c*d)

numpy array operations:
c+d: [5 7 9]
c*d: [ 4 10 18]


In [11]:
e = np.array([[1,2,3],[4,5,6]])
print('e:')
print(e)
print('e.sum(axis=0):', e.sum(axis=0)) 
print('e.sum(axis=1):', e.sum(axis=1))

e:
[[1 2 3]
 [4 5 6]]
e.sum(axis=0): [5 7 9]
e.sum(axis=1): [ 6 15]


In [12]:
# adding 1 D and 2 D arrays
f = np.array([[1,2,3],
            [4,5,6]])
g = np.array([10,20,30]) 
print("f+g:\n", f+g)

f+g:
 [[11 22 33]
 [14 25 36]]


In [13]:
# defining function with type definitions
from numpy import ndarray

def square(x: ndarray) -> ndarray: 
    '''
        Square each element in the input ndarray. 
    '''
    return np.power(x, 2)

def leaky_relu(x: ndarray) -> ndarray: 
    '''
        Apply "Leaky ReLU" function to each element in ndarray. 
    '''
    return np.maximum(0.2 * x, x)

In [14]:
# dynamic function calling example

from typing import Callable


def operate(a: int, b: int, func: Callable[[int, int], int]) -> int:
    return func(a, b)


def multiply(x: int, y: int) -> int:
    return x * y


result = operate(2, 3, multiply)
print(result) 

6


In [23]:

''' 
Note: The output of the first function become the input
to the next function so the arguments should match
e.g if we do a add with 2 numbers and then pass this to multiply
with 2 numbers then you would get an error 
Python TypeError missing 1 required positional argument
This is because when you add two numbers the results is a single number
This can't be passed to the multiple as its expecting two numbers
'''

# dynamic function calling in a chain
from typing import List

# create another function for add
def add(x: int, y: int) -> int:
    return x + y

def cube(x: int) -> int:
    return x ** 3

# create a chain
chain_function = Callable[[int, int], int]

# A Chain is a list of functions
NumbersChain = List[chain_function]

def chain_number_functions(chain: NumbersChain, x1: int, y1: int) -> int:
    '''
        Evaluates two functions in a row, in a "Chain". 
    '''
    assert len(chain) == 2, \
    "Length of input 'chain' should be 2"
    f1 = chain[0]
    f2 = chain[1]
    return f2(f1(x1,y1))

chain_result = chain_number_functions([add, cube], 2, 3)
print(chain_result) 

125
